# Generated by Django 6.0.3 on 2026-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_seed_nam_website_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thought",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
