# Generated by Django 6.0.3 on 2026-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_seed_first_thought"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="drawings/%Y/%m/")),
                ("category", models.CharField(choices=[("pencil", "Pencil"), ("camera", "Camera")], max_length=10)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
