# Generated by Django 6.0.3 on 2026-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_drawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Contribution calendar JSON from GitHub GraphQL API')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'GitHub contributions',
            },
        ),
    ]
