# Generated by Django 6.0.3 on 2026-04-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_channel_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('tier', models.CharField(choices=[('hidden', 'Hidden'), ('never_miss', 'Never Miss'), ('regular', 'Regular Rotation'), ('check_out', 'Worth Checking Out')], default='hidden', max_length=16)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('pinned', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='website.watchchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
