# Generated by Django 6.0.3 on 2026-04-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_watchchannel_watchvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('lichess_username', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
