# Generated by Django 6.0.3 on 2026-04-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_lichesstoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("commodity", "Commodity"),
                            ("crypto", "Crypto"),
                            ("bond", "Bond"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("alpha_vantage", "Alpha Vantage"), ("coingecko", "CoinGecko"), ("ecb", "ECB")],
                        max_length=16,
                    ),
                ),
                ("provider_id", models.CharField(max_length=128)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("change_pct", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="website.ticker"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["ticker", "-date"], name="website_pri_ticker__04b6da_idx")],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
