# Generated by Django 6.0.3 on 2026-04-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_add_watch_video_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitter_ip", models.GenericIPAddressField()),
                ("workspace", models.CharField(blank=True, default="", max_length=255)),
                ("trace_path", models.CharField(blank=True, default="", max_length=255)),
                ("token_count", models.IntegerField(default=0)),
                ("tool_calls", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="mission_status_created_idx"),
                    models.Index(fields=["submitter_ip", "-created_at"], name="mission_ip_created_idx"),
                ],
            },
        ),
    ]
