# Generated by Django 6.0.3 on 2026-04-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("oversize", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="downloads", to="website.turn"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [models.Index(fields=["turn", "id"], name="download_turn_idx")],
            },
        ),
    ]
