# Generated by Django 6.0.3 on 2026-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="listentrack",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
    ]
