# Generated by Django 6.0.3 on 2026-06-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_migrate_drawings_to_thoughts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drawing',
        ),
    ]
