# Generated by Django 6.0.3 on 2026-06-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_delete_drawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastfmCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=600, unique=True)),
                ('payload', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('artist', 'Artist'), ('album', 'Album'), ('track', 'Track')], max_length=8)),
                ('key', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('video_id', models.CharField(blank=True, default='', max_length=64)),
                ('play_count', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('in_library', models.BooleanField(default=False)),
                ('recommend_score', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['node_type'], name='website_mus_node_ty_dbba86_idx'), models.Index(fields=['-recommend_score'], name='website_mus_recomme_835a58_idx')],
                'unique_together': {('node_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MusicEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('similar_artist', 'Similar Artist'), ('similar_track', 'Similar Track'), ('colisten', 'Colisten'), ('structural', 'Structural')], max_length=16)),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='website.musicnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='website.musicnode')),
            ],
            options={
                'indexes': [models.Index(fields=['source'], name='website_mus_source__65a374_idx'), models.Index(fields=['target'], name='website_mus_target__02cd59_idx')],
                'unique_together': {('source', 'target', 'edge_type')},
            },
        ),
    ]
