# Generated by Django 6.0.3 on 2026-06-13 22:54

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_from_sync(apps, _schema_editor):
    """Mark existing sync-created rows so co-listen ignores their fabricated timestamps.

    Liked rows are always sync-created. Other recent rows (last 7 days) are almost
    certainly from the recent YTM syncs (history/liked/frequent inserted at ~now),
    whereas older rows are real-timestamp Takeout history worth keeping for co-listen.
    """
    ListenTrack = apps.get_model("website", "ListenTrack")
    cutoff = timezone.now() - timedelta(days=7)
    ListenTrack.objects.filter(is_liked=True).update(from_sync=True)
    ListenTrack.objects.filter(played_at__gte=cutoff).update(from_sync=True)


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0027_paperaccount_papertrade_papersnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="listentrack",
            name="from_sync",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_from_sync, migrations.RunPython.noop),
    ]
