# Generated by Django 6.0.3 on 2026-06-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0029_thought_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aoe2Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rec_file", models.FileField(blank=True, null=True, upload_to="aoe2/")),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("map_name", models.CharField(blank=True, default="", max_length=64)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("game_version", models.CharField(blank=True, default="", max_length=32)),
                ("my_civ", models.CharField(blank=True, default="", max_length=32)),
                ("my_result", models.CharField(blank=True, default="unknown", max_length=8)),
                ("my_elo", models.IntegerField(blank=True, null=True)),
                ("my_rating_change", models.IntegerField(blank=True, null=True)),
                ("opponent_civ", models.CharField(blank=True, default="", max_length=32)),
                ("opponent_elo", models.IntegerField(blank=True, null=True)),
                ("relic_match_id", models.BigIntegerField(blank=True, null=True)),
                ("relic_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("timeline", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("coach_analysis", models.TextField(blank=True, default="")),
                ("coach_model", models.CharField(blank=True, default="", max_length=64)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("done", "Done"),
                            ("error", "Error"),
                            ("skipped", "Skipped (not a 1v1)"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error_detail", models.TextField(blank=True, default="")),
                ("featured", models.BooleanField(default=False)),
                ("clip_url", models.URLField(blank=True, default="", max_length=500)),
                ("clip_title", models.CharField(blank=True, default="", max_length=120)),
                ("clip_note", models.CharField(blank=True, default="", max_length=300)),
                ("clip_start_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-played_at", "-created_at"],
            },
        ),
    ]
