# Generated by Django 6.0.3 on 2026-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0031_aoe2match_classifier_aoe2match_coach_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicnode",
            name="degree",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
