# Generated by Django 6.0.3 on 2026-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0031_aoe2match_classifier_aoe2match_coach_tier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("watching", "Watching"), ("adopted", "Adopted"), ("dropped", "Dropped")],
                        default="watching",
                        max_length=20,
                    ),
                ),
                ("is_new", models.BooleanField(default=True)),
                ("source", models.CharField(default="manual", max_length=100)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("stars", models.IntegerField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_reviewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added_at"],
                "indexes": [models.Index(fields=["status", "-added_at"], name="tool_status_added_idx")],
            },
        ),
    ]
