# Generated by Django 6.0.3 on 2026-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0032_musicnode_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicedge",
            name="source_kind",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="musicedge",
            name="edge_type",
            field=models.CharField(
                choices=[
                    ("structural", "Structural"),
                    ("tag", "Tag"),
                    ("affinity", "Affinity"),
                    ("similar_artist", "Similar Artist"),
                    ("similar_track", "Similar Track"),
                    ("colisten", "Colisten"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="musicnode",
            name="node_type",
            field=models.CharField(
                choices=[("artist", "Artist"), ("album", "Album"), ("track", "Track"), ("tag", "Tag")], max_length=8
            ),
        ),
    ]
