# Generated by Django 6.0.3 on 2026-09-18 12:48

import django.db.models.deletion
from django.db import migrations, models

import website.models.badminton


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0034_trackedtool"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadmintonPlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("height_m", models.FloatField(blank=True, null=True)),
                (
                    "hand",
                    models.CharField(
                        blank=True, choices=[("right", "Right"), ("left", "Left")], default="", max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BadmintonSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("pending", "Awaiting approval"),
                            ("approved", "Queued"),
                            ("running", "Analysing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=10,
                    ),
                ),
                ("recorded_on", models.DateField()),
                ("height_m", models.FloatField(blank=True, null=True)),
                ("hand", models.CharField(blank=True, default="", max_length=5)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("de", "Deutsch"), ("vi", "Tiếng Việt")], default="en", max_length=2
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "upload_key",
                    models.CharField(default=website.models.badminton._new_upload_key, max_length=32, unique=True),
                ),
                ("filename", models.CharField(max_length=200)),
                ("size_bytes", models.BigIntegerField()),
                ("received_bytes", models.BigIntegerField(default=0)),
                ("submitter_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("step", models.CharField(blank=True, default="", max_length=20)),
                ("stage", models.CharField(blank=True, default="", max_length=40)),
                ("error", models.TextField(blank=True, default="")),
                ("report", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="website.badmintonplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_on", "-created_at"],
            },
        ),
    ]
