from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health),
    path("auth/login/", views.auth_login),
    path("auth/check/", views.auth_check),
    path("bets/", views.bets_list),
    path("bets/create/", views.bets_create),
    path("bets/sync/", views.bets_sync),
    path("bets/sync-status/", views.bets_sync_status),
    path("bets/search/", views.bets_search),
    path("bets/<int:ticker_id>/history/", views.bets_history),
    path("bets/<int:ticker_id>/delete/", views.bets_delete),
    path("todo/", views.todo_list),
    path("projects/", views.project_list),
    path("thoughts/", views.thought_list),
    path("thoughts/create/", views.thought_create),
    path("feedback/", views.feedback_create),
    path("drawings/", views.drawing_list),
    path("drawings/upload/", views.drawing_upload),
    path("drawings/<int:drawing_id>/delete/", views.drawing_delete),
    path("github/contributions/", views.github_contributions),
    path("github/auth/", views.github_auth),
    path("github/callback/", views.github_callback),
    path("github/refresh-status/", views.github_refresh_status),
    path("lichess/auth/", views.lichess_auth),
    path("lichess/callback/", views.lichess_callback),
    path("lichess/token/", views.lichess_token),
    path("lichess/disconnect/", views.lichess_disconnect),
    path("lichess/explorer/<str:db>/", views.lichess_explorer),
    path("lichess/status/", views.lichess_status),
    path("listens/artists/", views.listen_top_artists),
    path("listens/albums/", views.listen_top_albums),
    path("listens/tracks/", views.listen_top_tracks),
    path("listens/recommended/", views.listen_recommended),
    path("listens/import/", views.listen_import),
    path("listens/", views.listen_list),
    path("listens/sync/", views.listen_sync),
    path("listens/stats/", views.listen_stats),
    path("listens/sync-status/", views.listen_sync_status),
    path("watches/recommended/", views.watch_recommended),
    path("watches/backfill-stats/", views.watch_backfill_stats),
    path("watches/", views.watch_list),
    path("watches/auth/", views.watch_auth),
    path("watches/callback/", views.watch_callback),
    path("watches/sync/", views.watch_sync),
    path("watches/sync-status/", views.watch_sync_status),
    path("watches/staging/", views.watch_staging),
    path("watches/channels/<int:channel_id>/tier/", views.watch_channel_tier),
    path("watches/channels/<int:channel_id>/order/", views.watch_channel_order),
    path("watches/channels/<int:channel_id>/uploads/", views.watch_channel_uploads),
    path("watches/channels/<int:channel_id>/pin-videos/", views.watch_channel_pin_videos),
    path("watches/channels/<int:channel_id>/delete/", views.watch_channel_delete),
    path("watches/videos/<int:video_id>/pin/", views.watch_video_pin),
    path("watches/videos/<int:video_id>/note/", views.watch_video_note),
    path("watches/videos/<int:video_id>/delete/", views.watch_video_delete),
]
