// AUTO-GENERATED — do not edit by hand. Regenerate via scripts/gen_aoe2_icons.py.
// Maps aoe2coach display names (techs / units / buildings / ages) to a bundled icon file
// under /aoe2-icons/ (sourced from SiegeEngineers/aoe2techtree, same-origin / CSP-safe).
//
// aoe2techtree names its icon PNGs by the genie *picture_index*, NOT the entity id. This map is
// built from aoe2techtree's per-civ tree JSONs (node_id / name -> picture_index -> file) and
// covers EVERY display name in aoe2coach const.py (UNIT_NAMES, BUILDING_NAMES, MILITARY_TECHS,
// UNIVERSITY_TECHS, ECO_TECHS, AGE_TECHS) — verified by frontend/src/lib/__tests__/aoe2Icons
// coverage test. A name absent here is a genuinely-unknown string (e.g. a brand-new unit not yet
// in const.py); the UI then renders a question-mark icon, never a broken image.

export const AOE2_ICON_BY_NAME: Record<string, string> = {
  Arambai: "unit_230.png",
  Arbalester: "unit_90.png",
  Archer: "unit_17.png",
  "Archery Range": "building_0.png",
  Architecture: "tech_14.png",
  "Armored Elephant": "unit_394.png",
  Arrowslits: "tech_119.png",
  Arson: "tech_118.png",
  "Ballista Elephant": "unit_231.png",
  Ballistics: "tech_25.png",
  Banking: "tech_3.png",
  Barracks: "building_2.png",
  "Battering Ram": "unit_74.png",
  "Battle Elephant": "unit_228.png",
  Berserk: "unit_38.png",
  Blacksmith: "building_4.png",
  "Blackwood Archer": "unit_549.png",
  "Blast Furnace": "tech_21.png",
  Bloodlines: "tech_110.png",
  "Bodkin Arrow": "tech_35.png",
  "Bolas Rider": "unit_547.png",
  "Bombard Cannon": "unit_30.png",
  "Bombard Tower": "building_42.png",
  "Bow Saw": "tech_71.png",
  Boyar: "unit_114.png",
  Bracer: "tech_37.png",
  "Camel Archer": "unit_191.png",
  "Camel Rider": "unit_78.png",
  "Camel Scout": "unit_392.png",
  "Cannon Galleon": "unit_55.png",
  "Cao Cao": "unit_465.png",
  "Capped Ram": "unit_63.png",
  Caravan: "tech_113.png",
  Caravanserai: "building_87.png",
  Caravel: "unit_198.png",
  Carrack: "unit_567.png",
  Castle: "building_7.png",
  "Castle Age": "age_base_castle_age.png",
  Cataphract: "unit_35.png",
  "Catapult Galleon": "unit_591.png",
  Cavalier: "unit_49.png",
  "Cavalry Archer": "unit_19.png",
  Centurion: "unit_405.png",
  "Chain Barding Armor": "tech_23.png",
  "Chain Mail Armor": "tech_22.png",
  "Chakram Thrower": "unit_390.png",
  "Champi Runner": "unit_555.png",
  "Champi Scout": "unit_540.png",
  "Champi Warrior": "unit_541.png",
  Champion: "unit_72.png",
  Chemistry: "tech_12.png",
  "Chu Ko Nu": "unit_36.png",
  Coinage: "tech_7.png",
  "Composite Bowman": "unit_407.png",
  Condottiero: "unit_134.png",
  Conquistador: "unit_106.png",
  Conscription: "tech_91.png",
  Coustillier: "unit_355.png",
  "Crop Rotation": "tech_0.png",
  Crossbowman: "unit_18.png",
  "Demolition Raft": "unit_202.png",
  "Demolition Ship": "unit_84.png",
  Dock: "building_13.png",
  Donjon: "building_84.png",
  "Double-Bit Axe": "tech_70.png",
  "Dragon Ship": "unit_178.png",
  Dromon: "unit_406.png",
  "Eagle Scout": "unit_109.png",
  "Eagle Warrior": "unit_148.png",
  "Elephant Archer": "unit_393.png",
  "Elite Arambai": "unit_504.png",
  "Elite Ballista Elephant": "unit_502.png",
  "Elite Battle Elephant": "unit_246.png",
  "Elite Berserk": "unit_485.png",
  "Elite Blackwood Archer": "unit_550.png",
  "Elite Bolas Rider": "unit_548.png",
  "Elite Boyar": "unit_494.png",
  "Elite Camel Archer": "unit_498.png",
  "Elite Cannon Galleon": "unit_298.png",
  "Elite Caravel": "unit_497.png",
  "Elite Cataphract": "unit_476.png",
  "Elite Centurion": "unit_521.png",
  "Elite Chakram Thrower": "unit_517.png",
  "Elite Champi Warrior": "unit_542.png",
  "Elite Chu Ko Nu": "unit_482.png",
  "Elite Composite Bowman": "unit_522.png",
  "Elite Conquistador": "unit_489.png",
  "Elite Coustillier": "unit_511.png",
  "Elite Eagle Warrior": "unit_149.png",
  "Elite Elephant Archer": "unit_93.png",
  "Elite Fire Archer": "unit_528.png",
  "Elite Fire Lancer": "unit_458.png",
  "Elite Gbeto": "unit_500.png",
  "Elite Genitour": "unit_499.png",
  "Elite Genoese Crossbowman": "unit_492.png",
  "Elite Ghulam": "unit_518.png",
  "Elite Guecha Warrior": "unit_544.png",
  "Elite Huskarl": "unit_478.png",
  "Elite Hussite Wagon": "unit_514.png",
  "Elite Ibirapema Warrior": "unit_552.png",
  "Elite Iron Pagoda": "unit_524.png",
  "Elite Jaguar Warrior": "unit_486.png",
  "Elite Janissary": "unit_480.png",
  "Elite Kamayuk": "unit_495.png",
  "Elite Karambit Warrior": "unit_503.png",
  "Elite Keshik": "unit_507.png",
  "Elite Kipchak": "unit_508.png",
  "Elite Kona": "unit_546.png",
  "Elite Konnik": "unit_506.png",
  "Elite Konnik (Dismounted)": "unit_506.png",
  "Elite Leitis": "unit_509.png",
  "Elite Liao Dao": "unit_525.png",
  "Elite Longboat": "unit_474.png",
  "Elite Longbowman": "unit_472.png",
  "Elite Magyar Huszar": "unit_493.png",
  "Elite Mameluke": "unit_479.png",
  "Elite Mangudai": "unit_484.png",
  "Elite Monaspa": "unit_523.png",
  "Elite Obuch": "unit_513.png",
  "Elite Organ Gun": "unit_496.png",
  "Elite Plumed Archer": "unit_488.png",
  "Elite Ratha (Melee)": "unit_389.png",
  "Elite Ratha (Ranged)": "unit_520.png",
  "Elite Rattan Archer": "unit_505.png",
  "Elite Samurai": "unit_483.png",
  "Elite Serjeant": "unit_512.png",
  "Elite Shotel Warrior": "unit_501.png",
  "Elite Shrivamsha Rider": "unit_519.png",
  "Elite Skirmisher": "unit_21.png",
  "Elite Steppe Lancer": "unit_274.png",
  "Elite Tarkan": "unit_487.png",
  "Elite Temple Guard": "unit_554.png",
  "Elite Teutonic Knight": "unit_477.png",
  "Elite Throwing Axeman": "unit_473.png",
  "Elite Tiger Cavalry": "unit_526.png",
  "Elite Turtle Ship": "unit_491.png",
  "Elite Urumi Swordsman": "unit_515.png",
  "Elite War Elephant": "unit_481.png",
  "Elite War Wagon": "unit_490.png",
  "Elite White Feather Guard": "unit_527.png",
  "Elite Woad Raider": "unit_475.png",
  Farm: "building_35.png",
  "Fast Fire Ship": "unit_85.png",
  Feitoria: "building_53.png",
  "Feudal Age": "age_base_feudal_age.png",
  "Fire Archer": "unit_436.png",
  "Fire Galley": "unit_203.png",
  "Fire Lancer": "unit_457.png",
  "Fire Ship": "unit_86.png",
  "Fish Trap": "building_41.png",
  "Fishing Ship": "unit_24.png",
  "Flaming Camel": "unit_270.png",
  "Flemish Militia": "unit_354.png",
  Fletching: "tech_34.png",
  Folwark: "building_86.png",
  Forging: "tech_17.png",
  "Fortified Church": "building_88.png",
  "Fortified Wall": "building_32.png",
  Galleon: "unit_60.png",
  Galley: "unit_87.png",
  Gate: "building_36.png",
  "Gate (variant)": "building_36.png",
  Gbeto: "unit_197.png",
  Genitour: "unit_201.png",
  "Genoese Crossbowman": "unit_133.png",
  Ghulam: "unit_385.png",
  Gillnets: "tech_41.png",
  "Gold Mining": "tech_15.png",
  "Gold Shaft Mining": "tech_62.png",
  Grenadier: "unit_462.png",
  "Guard Tower": "building_27.png",
  "Guecha Warrior": "unit_543.png",
  Guilds: "tech_58.png",
  Halberdier: "unit_104.png",
  "Hand Cannoneer": "unit_22.png",
  "Hand Cart": "tech_42.png",
  Harbor: "building_56.png",
  "Heated Shot": "tech_104.png",
  "Heavy Camel Rider": "unit_79.png",
  "Heavy Cavalry Archer": "unit_71.png",
  "Heavy Demo Ship": "unit_83.png",
  "Heavy Demolition Ship": "unit_83.png",
  "Heavy Hei Guang Cavalry": "unit_430.png",
  "Heavy Plow": "tech_1.png",
  "Heavy Rocket Cart": "unit_460.png",
  "Heavy Scorpion": "unit_89.png",
  "Hei Guang Cavalry": "unit_429.png",
  "Horse Collar": "tech_2.png",
  Houfnice: "unit_372.png",
  House: "building_34.png",
  Hulk: "unit_566.png",
  Husbandry: "tech_10.png",
  Huskarl: "unit_50.png",
  Hussar: "unit_103.png",
  "Hussite Wagon": "unit_370.png",
  "Ibirapema Warrior": "unit_551.png",
  "Imperial Age": "age_base_imperial_age.png",
  "Imperial Camel Rider": "unit_185.png",
  "Imperial Skirmisher": "unit_229.png",
  "Iron Casting": "tech_18.png",
  "Iron Pagoda": "unit_461.png",
  "Jaguar Warrior": "unit_110.png",
  Janissary: "unit_39.png",
  "Jian Swordsman": "unit_437.png",
  Kamayuk: "unit_97.png",
  "Karambit Warrior": "unit_233.png",
  Keep: "building_26.png",
  Keshik: "unit_251.png",
  Kipchak: "unit_252.png",
  Knight: "unit_1.png",
  Kona: "unit_545.png",
  Konnik: "unit_249.png",
  "Konnik (Dismounted)": "unit_249.png",
  Krepost: "building_55.png",
  "Leather Archer Armor": "tech_50.png",
  Legionary: "unit_139.png",
  Leitis: "unit_253.png",
  "Liao Dao": "unit_463.png",
  "Light Cavalry": "unit_91.png",
  "Liu Bei": "unit_466.png",
  "Long Swordsman": "unit_13.png",
  Longboat: "unit_40.png",
  Longbowman: "unit_41.png",
  Loom: "tech_6.png",
  "Lou Chuan": "unit_431.png",
  "Lumber Camp": "building_40.png",
  "Magyar Huszar": "unit_99.png",
  Mameluke: "unit_37.png",
  "Man-at-Arms": "unit_10.png",
  Mangonel: "unit_27.png",
  Mangudai: "unit_42.png",
  Market: "building_16.png",
  Masonry: "tech_13.png",
  Militia: "unit_8.png",
  Mill: "building_19.png",
  "Mining Camp": "building_39.png",
  Missionary: "unit_107.png",
  Monaspa: "unit_408.png",
  Monastery: "building_10.png",
  Monk: "unit_33.png",
  "Mounted Trebuchet": "unit_464.png",
  "Mule Cart": "building_89.png",
  "Murder Holes": "tech_61.png",
  Obuch: "unit_369.png",
  Onager: "unit_101.png",
  "Organ Gun": "unit_190.png",
  Outpost: "building_38.png",
  "Padded Archer Armor": "tech_49.png",
  Paladin: "unit_2.png",
  "Palisade Gate": "building_44.png",
  "Palisade Wall": "building_30.png",
  "Parthian Tactics": "tech_111.png",
  Pasture: "building_96.png",
  Petard: "unit_113.png",
  Pikeman: "unit_11.png",
  "Plate Barding Armor": "tech_65.png",
  "Plate Mail Armor": "tech_64.png",
  "Plumed Archer": "unit_108.png",
  "Ratha (Melee)": "unit_389.png",
  "Ratha (Ranged)": "unit_389.png",
  "Rattan Archer": "unit_232.png",
  "Ring Archer Armor": "tech_51.png",
  "Rocket Cart": "unit_459.png",
  Samurai: "unit_44.png",
  Savar: "unit_410.png",
  "Scale Barding Armor": "tech_66.png",
  "Scale Mail Armor": "tech_63.png",
  Scorpion: "unit_80.png",
  "Scout Cavalry": "unit_64.png",
  Serjeant: "unit_356.png",
  Settlement: "building_98.png",
  "Shotel Warrior": "unit_195.png",
  "Shrivamsha Rider": "unit_391.png",
  "Siege Elephant": "unit_395.png",
  "Siege Engineers": "tech_101.png",
  "Siege Onager": "unit_102.png",
  "Siege Ram": "unit_73.png",
  "Siege Tower": "unit_212.png",
  "Siege Workshop": "building_22.png",
  Skirmisher: "unit_20.png",
  Slinger: "unit_143.png",
  Spearman: "unit_31.png",
  "Spies/Treason": "tech_19.png",
  Squires: "tech_80.png",
  Stable: "building_23.png",
  "Steppe Lancer": "unit_273.png",
  "Stone Mining": "tech_87.png",
  "Stone Shaft Mining": "tech_88.png",
  "Stone Wall": "building_31.png",
  "Sun Jian": "unit_467.png",
  Supplies: "tech_174.png",
  Tarkan: "unit_105.png",
  "Temple Guard": "unit_553.png",
  "Teutonic Knight": "unit_45.png",
  Thirisadai: "unit_387.png",
  "Throwing Axeman": "unit_46.png",
  "Thumb Ring": "tech_112.png",
  "Tiger Cavalry": "unit_432.png",
  "Town Center": "building_28.png",
  "Town Patrol": "tech_89.png",
  "Town Watch": "tech_69.png",
  Tracking: "tech_83.png",
  "Traction Trebuchet": "unit_428.png",
  "Trade Cart": "unit_34.png",
  "Trade Cog": "unit_23.png",
  "Transport Ship": "unit_95.png",
  "Treadmill Crane": "tech_60.png",
  Trebuchet: "unit_29.png",
  "Turtle Ship": "unit_116.png",
  "Two-Handed Swordsman": "unit_12.png",
  "Two-Man Saw": "tech_81.png",
  University: "building_33.png",
  "Urumi Swordsman": "unit_386.png",
  Villager: "unit_15.png",
  "War Elephant": "unit_43.png",
  "War Galley": "unit_25.png",
  "War Hulk": "unit_565.png",
  "War Wagon": "unit_117.png",
  "Warrior Priest": "unit_409.png",
  "Watch Tower": "building_25.png",
  Wheelbarrow: "tech_79.png",
  "White Feather Guard": "unit_434.png",
  "Winged Hussar": "unit_371.png",
  "Woad Raider": "unit_47.png",
  Wonder: "building_37.png",
  "Xianbei Raider": "unit_433.png",
  "Xolotl Warrior": "unit_109.png",
};

/** Resolve an aoe2coach name to its bundled icon URL, or null when unmapped. */
export function aoe2IconUrl(name: string | null | undefined): string | null {
  if (!name) return null;
  const f = AOE2_ICON_BY_NAME[name];
  return f ? `/aoe2-icons/${f}` : null;
}

// The four gatherable resources, with their real AoE2 DE resource-pile icons (sourced from
// SiegeEngineers/aoe2techtree img/<resource>.png, same-origin / CSP-safe) — used as the colored
// legend in the economy graphs. Colors match the in-game resource hues.
export const AOE2_RESOURCE_ICON: Record<string, string> = {
  food: "/aoe2-icons/resource_food.png",
  wood: "/aoe2-icons/resource_wood.png",
  gold: "/aoe2-icons/resource_gold.png",
  stone: "/aoe2-icons/resource_stone.png",
};

/** Resolve a resource name (food/wood/gold/stone) to its bundled resource-pile icon URL. */
export function aoe2ResourceIconUrl(resource: string): string | null {
  return AOE2_RESOURCE_ICON[resource] ?? null;
}
